rules:
  unpinned-uses:
    config:
      policies:
        "actions/*": ref-pin
        "codecov/codecov-action": ref-pin
        "pypa/gh-action-pypi-publish": ref-pin
        "SonarSource/sonarqube-scan-action": ref-pin
