version: 2

sphinx:
  configuration: docs/source/conf.py

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
  jobs:
    post_create_environment:
      - pip install --upgrade pip
      - pip install --group dev
