name: Package and Publish
on: [push]
jobs:
  package:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools twine wheel
    - name: Package
      run: |
        python setup.py sdist bdist_wheel
    - name: Publish to TestPyPi
      if: github.ref == 'refs/heads/master'
      uses: pypa/gh-action-pypi-publish@v1.0.0a0
      with:
        user: __token__
        password: ${{ secrets.test_pypi_token }}
        repository_url: https://test.pypi.org/legacy/
